version: "3.9"

services:
  ghofle_postgres:
    image: postgres:latest
    container_name: go_storage_postgres_container
    hostname: ${DB_HOST}
    command: -p ${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /data/postgres
    volumes:
      - ../data/go_storage/postgres:/data/postgres
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: unless-stopped
    networks:
      - main_go_storage_go_network

  redis:
    container_name: ${REDIS_HOST}
    hostname: ${REDIS_HOST}
    image: redis:latest
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
    volumes:
      - ./redis.conf:/usr/local/etc/redis.conf
    networks:
      - main_go_storage_go_network

networks:
  main_go_storage_go_network:
